version: '3'

services:
  hns-backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    image: kcwong395/hidenseek-hns-backend:latest
    

  hns-frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    image: kcwong395/hidenseek-hns-frontend:latest
