version: '3'

services:
  hns-backend:
    build: ./backend
    command: flask run
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "3000"

  hns-frontend:
    build: ./frontend
    command: npm start
    restart: always
    ports:
      - "3000:3000"