version: '3'

services:
  hns-backend:
    build: ./backend
    command: flask run --host=0.0.0.0
    restart: always

  hns-frontend:
    build: ./frontend
    command: npm start
    restart: always
    ports:
      - "3000:3000"
