version: 2.1

orbs:
  python: circleci/python@1.2
  terraform: circleci/terraform@3.0.0
  azure-cli: circleci/azure-cli@1.2.0

jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/project
    steps:
      - checkout
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - run: docker-compose build
      - run: docker-compose push
  deploy:
    executor: azure-cli/azure-docker
    steps:
      - run: az login --service-principal -u $AZURE_APPID -p $AZURE_PASS --tenant $AZURE_TENANT
      - run: az container restart --name HideNSeekContainer --resource-group HideNSeek
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          context: Dockerhub
      - deploy:
          context: Azure
          requires:
            - build