version: 2.1

orbs:
  python: circleci/python@1.2
  terraform: circleci/terraform@3.0.0
  azure-cli: circleci/azure-cli@1.2.0

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/backend  # If you're requirements.txt isn't in the root directory.
          pip-dependency-file: requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # Run the tests placed under backend/tests
          command: python -m unittest discover -s backend/tests -p "test_*.py" -v
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/project
    steps:
      - checkout
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - run: docker-compose build
      - run: docker-compose push
  deploy:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-user
      - run: az restart HideNSeek
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      #- test
      #- build:
      #    context: Dockerhub
      #    requires:
      #      - test
      - deploy:
          context: Azure
      #    requires:
      #      - build